# Generated by Django 5.2.8 on 2025-11-24 11:59

import common.models
import utils.file
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("username", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "email",
                    common.models.NormalizedEmailField(max_length=255, unique=True),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_email_verified", models.BooleanField(default=False)),
                ("email_verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "email_verification_token",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True,
                        max_length=500,
                        null=True,
                        upload_to=utils.file.dynamic_upload_path,
                    ),
                ),
                ("otp", models.CharField(blank=True, max_length=8, null=True)),
                ("otp_expiry", models.DateTimeField(blank=True, null=True)),
                ("otp_sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["username"], name="user_username_idx"),
                    models.Index(fields=["is_active"], name="user_is_active_idx"),
                    models.Index(
                        fields=["is_email_verified"], name="user_is_email_verified_idx"
                    ),
                    models.Index(
                        fields=["email_verification_token"],
                        name="email_verification_token_idx",
                    ),
                    models.Index(fields=["created_at"], name="user_created_at_idx"),
                    models.Index(fields=["otp_expiry"], name="user_otp_expiry_idx"),
                    models.Index(fields=["is_staff"], name="user_is_staff_idx"),
                    models.Index(fields=["is_superuser"], name="user_is_superuser_idx"),
                    models.Index(
                        fields=["is_active", "is_email_verified"],
                        name="user_active_verified_idx",
                    ),
                    models.Index(
                        fields=["is_active", "created_at"],
                        name="user_active_created_at_idx",
                    ),
                ],
            },
        ),
    ]
